### PR TITLE
Move utils imports in to template tag functions

### PR DESCRIPTION
**Pull request by edrik**
Could this be a possible fix for #71 :thinking:

### CODE REVIEW

**Comment by lemonsaurus** [comment]
This is interesting. That might just work.

**Comment by perlun** [comment]
@lemonsaurus @edrik Sounds really nice. How do we proceed with this, do you want to merge it right away or should I test it locally somehow to see if it resolves my issue?

**Comment by lemonsaurus** [comment]
If you were able to test it locally, that would be extremely convenient. The hacky, easy way to test it is to just copy paste the code from this pull request straight into your virtual environment install, under `/your/venv/folder/lib/python3.x/site-packages/django_simple_bulma/templatetags`.

**Comment by perlun** [comment]
Hacks are perfectly fine at this stage... :grin: 

The only problem is that this is rather intermittent. I just tried to run `./manage.py runserver` 10 times and couldn't reproduce the issue a single time.

I applied the changes from here (thanks @edrik :pray:), and it worked similarly. 10 times, no exceptions.

So, it at least doesn't seem to make things _worse_ at least. :grin: I can keep the changes for now and will report back if I see it again or not within the next few days.

**Comment by lemonsaurus** [comment]
Actually, I'll just merge this and add it to 2.3.1, it's fine.

**Pull request merged**
